[project]
name = "hospital-patient-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker==40.1.2",
    "python-dotenv==1.2.1",
]
